3371 Spike Cypress testing
ONSdigital/ssdc-rm-ui-tests pull request #1
Opened 2022-04-27 07:20 UTC by liamtoozer

# Motivation and Context

We want to start testing our response operations UI in our CI environment, using the [tests from a previous spike](https://github.com/ONSdigital/ssdc-rm-response-operations/blob/b22145f4a59c383862a0d47cc73b4f7207ba2290/ui/cypress/integration/CreateSurvey.js)

# What has changed

* Copied across test from older spike and configured to allow `baseURL` to be used
* Added Dockerfile, pod manifest, and task ready for CI

# How to test?

Checkout the other branches and follow the instructions on the ticket

# Links

[Trello](https://trello.com/c/sHrZEWg3)

2022-04-27 14:23 UTC, AdamHawtin requested changes
I think some README words on pre-requisites/running/developing the tests are needed.

2022-04-27 14:42 UTC, AdamHawtin reviewed
I've also got an intermittent failure locally with 
```     AssertionError: Timed out retrying after 4000ms: expected 'http://localhost:7777/createsurvey' to include '/surveys?flashMessageUntil'```

I can see in the test video (great feature!) that the page with the flashed message did load, but slightly after that test assertion failed, I think the test perhaps just didn't wait quite long enough for the redirect, since it depends on a pubsub confirmed publish it can take a couple of seconds to redirect to that page. Can the tests be made to allow a longer timeout on that assertion to make them less flaky?

2022-04-29 08:13 UTC, ryangrundy7 approved these changes
Works locally and in GCP 👍

2022-04-29 11:02 UTC, davidmort approved these changes
this looks good and think it will benefit us a lot when we start doing more ui stuff, we will need to think about how we want this do work in our pipelines and how we manage all the screenshot/video files that get generated, but this is a good start

2022-05-03 10:09 UTC, AdamHawtin commented on Makefile
> +	npm install cypress@9.6.0
I think this should just be an `npm install`, the required package should be specified in the package.json not in this command.

2022-05-03 12:36 UTC, AdamHawtin approved these changes

2022-05-05 06:56 UTC, merged